namespace: demo

replicaCount: 2

image:
  repository: devops-demo
  tag: "1.0"

containerPort: 8080

service:
  nodePort: 30080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
