apiVersion: v1
kind: Service
metadata:
  name: devops-demo
  namespace: demo
spec:
  type: NodePort
  selector:
    app: devops-demo
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
