name: CI-CD

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/devops-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build app
        run: dotnet build app/app.csproj --configuration Release

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ github.sha }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm upgrade (deploy)
        run: |
          helm upgrade devops-demo ./devops-demo \
            --install \
            -n demo \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=${{ github.sha }}
